version: '3.7'

services:
  frontend:
    build:
      context: ./${SERVERNAME}
      args:
        NODEVERSION: ${NODEVERSION}
        SERVERNAME: ${SERVERNAME}
        REACT_APP_PATH: ${REACT_APP_PATH}
    expose:
      - ${REACT_APP_PORT}
    environment:
      - PROTOCOL=${REACT_APP_PROTOCOL}
      - HOST=${REACT_APP_HOST}
      - PORT=${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes:
      - ${SERVERNAME}:/srv/app/${SERVERNAME}
    command: npm run start

volumes:
  frontend:
    driver: local
    driver_opts:
      type: none
      device: $PWD/${SERVERNAME}/scribble
      o: bind
